# Generated by Django 5.2.6 on 2025-09-15 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ball', 'Ball'), ('sock', 'Sock'), ('boots', 'Boots'), ('shinguard', 'Shinguard'), ('jersey', 'Jersey'), ('hat', 'Hat'), ('glove', 'Glove')])),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
