# Generated by Django 5.2.6 on 2025-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ball', 'Ball'), ('sock', 'Sock'), ('boots', 'Boots'), ('shinguard', 'Shinguard'), ('jersey', 'Jersey'), ('hat', 'Hat'), ('glove', 'Glove')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
